version: '3'

services:
  pixman:
    image: pixman/pixman
    container_name: pixman
    ports:
      - "${PIXMAN_PORT}:5000"
    environment:
      - MYTVSUPER_TOKEN=${MYTVSUPER_TOKEN}
    restart: always

  thetv:
    image: dtankdemp/thetvapp-m3u:latest
    container_name: thetv
    ports:
      - "${THETV_PORT}:4124"
    restart: always

  aktv:
    image: 4proxy  # 假设您已经构建了包含 AKTV 的镜像
    container_name: aktv
    ports:
      - "${AKTV_PORT}:${AKTV_PORT}"
    environment:
      - AKTV_HOST=${AKTV_HOST}
      - AKTV_PORT=${AKTV_PORT}
    restart: always

  streamshield-proxy:
    image: ppyycc/streamshield-proxy:latest
    container_name: streamshield-proxy
    ports:
      - "${STREAMSHIELD_PORT}:4994"
    environment:
      - CUSTOM_DOMAIN=${CUSTOM_DOMAIN}
      - VPS_HOST=${VPS_HOST}
      - SECURITY_TOKEN=${SECURITY_TOKEN}
      - INCLUDE_MYTVSUPER=${INCLUDE_MYTVSUPER}
      - THETV_SOURCE=${THETV_SOURCE}
      - CHINAM3U=${INCLUDE_CHINA_M3U}
      - AKTV_HOST=${AKTV_HOST}
      - AKTV_PORT=${AKTV_PORT}
    restart: always
    depends_on:
      - pixman
      - thetv
      - aktv

networks:
  default:
    driver: bridge
